#error_codes.py handles:
# central list of error codes
# keeps errors consistent across modules

INVALID_FLOOR = "INVALID_FLOOR"
ELEVATOR_NOT_FOUND = "ELEVATOR_NOT_FOUND"
ELEVATOR_OUT_OF_SERVICE = "ELEVATOR_OUT_OF_SERVICE"
#
DOOR_OPEN_CONFLICT = "DOOR_OPEN_CONFLICT"
OVERLOAD = "OVERLOAD"
EMERGENCY_ACTIVE = "EMERGENCY_ACTIVE"
